name: Format C++ Code

on:
  push:
    branches:
      - '**'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Clang Format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Format code
      run: |
        find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\)' -exec clang-format -style="{ BasedOnStyle: Google, PointerAlignment: Left, ColumnLimit: 110}" -i {} \;

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply clang-format to mantain the style
        commit_user_name: Clang Format Bot
        commit_user_email: bot@example.com
        commit_author: clang-format auto committer <bot@example.com>
